-	/**
-	 * Created by Admin on 26.03.14.
-	 */
-	'use strict'
-	var req;
-	var getTimeUrl;
-	
-	function getXmlHttp(){
-	 if (window.XMLHttpRequest)
-	 {
-	     try
-	     {
-	         return new XMLHttpRequest();
-	     }
-	    catch (e) {}
-	 }
-	 else if (window.ActiveXObject)
-	 {
-	     try
-	     {
-	         return new ActiveXObject('Msxml2.XMLHTTP');
-	     } catch (e){}
-	     try
-	     {
-	         return new ActiveXObject('Microsoft.XMLHTTP');
-	     } catch (e) {}
-	 }
-	 return null;
-	};
-	
-	function showDemo () {
-	    var url= location.href;
-	    var request = getXmlHttp();
-	    request.open("GET", url,false);
-	    request.send(null);
-	    alert (request.responseText);
-	};
-	
-	function showAsyncRequest () {
-	    getTimeUrl = "gettime.php?delay=1";
-	    req = getXmlHttp();
-	    req.onreadystatechange = showAsyncRequestComplete;
-	    req.open("GET", getTimeUrl, true);
-	    req.send (null);
-	}
-	
-	function showAsyncRequestComplete() {
-	 if (req.readyState == 4){
-	   if(req.status == 200) {
-	     var result = document.getElementById("asyncresult");
-	     result.firstChild.nodeValue = req.responseText;
-	     req = null;
-	   }
-	 }
-	};
-	
-	var timer = setInterval(function(){showAsyncRequest()}, 1000);
